### ISSUE TITLE
Crashes with Apple Watch Series 3

### ISSUE THREAD

**Issue by motocodeltd** [tikhop/ASN1Swift#1]
Hi,

Using latest TPInAppReceipt in shared code in WatchOS and iOS. I have some crash reports coming in from WatchOS only (code identical to iOS).  Unfortunately symbolication fails for some reason (I import TPInAppReceipt as a swift package manager module, and i think there's a bitcode related bug here). So the obfuscated trace looks like this:

0   -      	0x000c70b6 _hidden#590_ + 40 (__hidden#69_:0)
1   -      	0x000c73ca __hidden#93_ + 22 (__hidden#69_:0)
2   -      	0x000c73ca _hidden#592_ + 38
3   libswiftCore.dylib            	0x6dc1af14 dispatch thunk of Decodable.init(from:) + 12
4   -     	0x000e55e6 _hidden#222_ + 774 (__hidden#643_:1575)
5   -     	0x000df70a __hidden#772_ + 32 (__hidden#643_:1547)
6   -      	0x000df70a ASN1Decoder.decode<A>(_:from:template:) + 340 (__hidden#643_:46)
7   -      	0x000d99b6 _hidden#2010_ + 138 (__hidden#2074_:63)
8  -      	0x000d1250 InAppReceipt.init(receiptData:rootCertPath:) + 34 (__hidden#69_:0)

I appreciate this is not very useful, but just wanted to start a discussion in case someone else is aware of this.

Thanks again!

**Comment by tikhop** [comment]
@motocodeltd Just released version 1.2.3 with a potential fix.

**Comment by motocodeltd** [comment]
Thanks for this - I've shipped a workaround to my users and I've also asked a few to opt in to some debugging information that will send me their receipt. I will then try to replicate on a Series 3 and if I replicate, I will post the crash dump and then try your fix. Really appreciate your help.

**Comment by tikhop** [comment]
@motocodeltd sounds good. 

I'm waiting for iphone 4s to try this library out on 32bit arm.

**Comment by motocodeltd** [comment]
I have finally managed to replicate this.

I was not able to replicate it on a series 3 while running via xcode but i *was* able to replicate it when running a build on a series 3 deployed via testflight. I have a feeling it might be bitcode related, like this one:

https://github.com/Alamofire/Alamofire/issues/3295
https://developer.apple.com/forums/thread/659130

I have not received a crash report from test flight yet.

I want to try a few more things, like running a RELEASE build via xcode, more debugging info, plus of course your fix.

i also wonder if this is indeed a bitcode Apple bug, what todo for these users (if arm32 / series03, fallback on something else?)

**Comment by motocodeltd** [comment]
initial testing appears to show that the crash doesn't happen with the new version of ASN1Swift, but i've yet to run my full test suite

**Comment by motocodeltd** [comment]
Right, so after extensive testing last night:

The crash happens *only* (but reliably) on an actual S03, with or without the fix (i.e. new version of ANS1Swift), *only* on testflight builds and *only* when ASN1Swift is imported as a framework with SPM. I haven't tried carthage or cocoapods, but If I just include the source code in my project and ship a test flight build, I can parse the receipt without any problems.

This is bizarre and IMO further supports the bitcode Apple bug scenario. Is there anything else you'd like me to try?

Thanks

**Comment by tikhop** [comment]
Hi Stefanos,

I'm sorry to hear that you are still fighting this issue and my workaround didn't fix the problem. I'd love to fix it in a right way, but I really don't know what I can do here. I went thru the code again and again and I just don't know what may cause the crash. I wish we had a more detailed crash log.

We can try to log all decoding steps and see when the crash occurs. 

If you want, hit me up on telegram (@tikhop) and we can try something out.

**Comment by motocodeltd** [comment]
It's a tricky one - I'm opened a feedback with Apple - FB8732976. I've also managed to replicate it with this piece of code (when running via testflight and as a swift module, on a series 3 only). String is a base64 encoded receipt.

let string = "REMOVED RECEIPT"
        let data = Data(base64Encoded: string)
        let asn1decoder = ASN1Swift.ASN1Decoder()
        let _ = try! asn1decoder.decode(PKCS7Container.self, from: data!)


Last line produces the crash (and data is not nil).

**Comment by tikhop** [comment]
Thanks for the receipt, I will take a look tonight.

**Comment by schwmi** [comment]
Hi, I had a look at the library today because I am thinking about replacing OpenSSL with a more lightweight swift parser. Could this crash be related to some decoding values via
`try valueContainer.decode(Int.self)`? As it is crashing on 32bit devices it may help to be more explicit by stating `try valueContainer.decode(Int64.self)`

**Comment by tikhop** [comment]
Hi, I was thinking about that, but if it so — then, we have a problem with a compiler, as I know `Int` on 32bit device must be `Int32` under the hood. 

Since the crash happens (I assume) during decoding step, my first attempt was to fix guid deserialization method, I was explicitly using `Int64` there.

**Comment by schwmi** [comment]
Don't think that it must be a compiler problem. If we deserialize e.g the `webOrderLineItemID` via `try valueContainer.decode(Int.self)` on a 32 bit device, an Int32 is provided for this field. As the `webOrderLineItemID` is most of the time larger and 2^31 I would assume the code to crash/throw. On 64 bit devices this isn't a problem as a Int64 is provided.

**Comment by tikhop** [comment]
I see your point. 

Right, in case of `webOrderLineItemID`, it will definitely crash/throw. 
Honestly, I didn't even think that we can get a value larger than possible.

**Comment by motocodeltd** [comment]
For the record I haven't had a single crash since I shipped 8c48a0d0c0708c44243d98fdbac5eea6564d1c9e without using the swift package manager, but by including the source code in my app.

**Comment by tikhop** [comment]
@motocodeltd good to know. I've tried your receipt from Apple Watch and couldn't reproduce the crash. I assume, here, we have, as you stated before, a bitcode related bug.

**Comment by patrickferreira** [comment]
Hi, I am also having the same bug using Swift Package Manager and Alamofire on watchOS.
I switched back to cocoapods and no more crash.

Hope it helps!
