### ISSUE TITLE
Target folder is lowercase

### ISSUE THREAD

**Issue by trilorez** [tikhop/ASN1Swift#2]
When including this package in an Xcode project, I get the following warning during the `Resolve Package Graph` build step:

> the target name ASN1Swift has different case on the filesystem and the Package.swift manifest file

It looks the target folder in the filesystem is `asn1swift` when it should be `ASN1Swift`.

**Comment by tikhop** [comment]
@trilorez I will fix it in the next release. 
Thank you!

**Comment by holtwick** [comment]
Same here

<img width="659" alt="Holtwick-Xcode-2020-qYBGGsWi@2x" src="https://user-images.githubusercontent.com/49557/96738430-fe886e00-13be-11eb-8960-26f1a40f5cd9.png">

![Holtwick-Xcode-2020-yU6BCUTi@2x](https://user-images.githubusercontent.com/49557/96738522-19f37900-13bf-11eb-9c8b-4cd2a86a65a5.png)
