### ISSUE TITLE
Extract R and S values for ASN1 signature?

### ISSUE THREAD

**Issue by yspreen** [tikhop/ASN1Swift#4]
I'm trying to extract the R and S values (as Data) from a Data stream. Is that possible with this project? Thanks

**Comment by tikhop** [comment]
Hi @yspreen, I'm sorry for the late response. I have been off the grid for the last 3 weeks. 

I believe we can extract any data we want from any asn1 data stream. Unfortunately, I haven't tried to parse anything, but Apple in-app receipt which is just a pcks7 file, but I don't see any problems to do so. If we know the asn1 structure 
of incoming data, then we can declare a struct and decode asn1 data into this struct.

Do you have a base64 string of data you want to parse?

**Comment by yspreen** [comment]
I envy your off-the-grid-ness ;)

So the use-case is quite narrow, and I decided to implement it without the use of a library. It would've been overkill. Here's the code: https://github.com/eu-digital-green-certificates/dgca-app-core-ios/blob/main/Sources/Services/ASN1.swift
