### ISSUE TITLE
Filename case error?

### ISSUE THREAD

**Issue by ceramicatheist** [tikhop/ASN1Swift#5]
When using ASN1Swift in Xcode 12, as a SPM Package, I get this warning during build:

> the target name ASN1Swift has different case on the filesystem and the Package.swift manifest file

Unhelpfully, it doesn't point out which exact file is the problem; and Git famously does not accommodate MacOS' case-insensitive filesystem all that well (it makes it difficult to commit a filename case change, since the file name is the "same" in mac world.)

This is minor, since the package still works fine; but: is it possible that some file has correct case on your development machine's filesystem, but got into Git with the wrong case somehow?

**Comment by tikhop** [comment]
Hi @ceramicatheist, I'll fix it next week.

**Comment by tikhop** [comment]
Hi @ceramicatheist, sorry for the delay. 

Seems like it's already fixed. https://github.com/tikhop/ASN1Swift/issues/2

Are you using the last version?

**Comment by ceramicatheist** [comment]
I definitely was at the time I filed this.
Fortunately the project in question has passed on to a new owner. I'll drop them a note
