### ISSUE TITLE
minor typo errors

### ISSUE THREAD

**Issue by Reza-Rajabi** [tikhop/ASN1Swift#6]
the word `read` should read `real` in [this](https://github.com/tikhop/ASN1Swift/blob/277cbea813fecb15b714501ca06869c11bbd54b7/Sources/ASN1Swift/ASN1Types.swift#L120) line.

[this](https://github.com/tikhop/ASN1Swift/blob/277cbea813fecb15b714501ca06869c11bbd54b7/Sources/ASN1Swift/PKCS7/PKCS7.swift#L310) name (CetrificatesContaner) is misspelled.

**Comment by tikhop** [comment]
Hello @Reza-Rajabi, it was fixed in [v1.2.5](https://github.com/tikhop/ASN1Swift/releases/tag/1.2.5). Thank you!
