### ISSUE TITLE
Any support of Privacy Manifest?

### ISSUE THREAD

**Issue by iharkatkavets** [tikhop/ASN1Swift#8]
Privacy Updates for AppStore submission

## Expected Behavior
Developers are responsible for all code included in their apps. At WWDC23, Apple introduced new privacy manifests and signatures for commonly used third-party SDKs and announced that developers will need to declare approved reasons for using a set of APIs in their app’s privacy manifest.

## Current Behavior
The library doesn't provide Privacy Manifest file

## Possible Solution
The library should provide Privacy Manifest if it collects information or access "Required Reasons API"

## Additional Info
<img width="826" alt="Screenshot 2024-03-08 at 09 26 02" src="https://github.com/tikhop/ASN1Swift/assets/1083951/0121e09a-e5ec-4224-80be-3d5ca331d1c0">

**Comment by tikhop** [comment]
Hi @iharkatkavets, thanks for bringing this up. 

I have added Privacy Manifest [here ](https://github.com/tikhop/ASN1Swift/commit/4e525ca3064fd45751b80c9ae6a2c16ea7b395e9).
